$(document).ready(function(){
	$('.slider__hair').slick({
		autoplay:true,
		autoplaySpeed:1000,
		pauseOnHover:false,
		touchThreshold:10,
		waitForAnimate:false
	});
	$('.slider__nail').slick({
		autoplay:true,
		autoplaySpeed:1000,
		pauseOnHover:false,
		touchThreshold:10,
		waitForAnimate:false
	});
	$('.slider__cosm').slick({
		autoplay:true,
		autoplaySpeed:1000,
		pauseOnHover:false,
		touchThreshold:10,
		waitForAnimate:false
	});
});